{{- if .Values.fileserver.create }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "deepfence-console.fullname" . }}-secrets-fileserver
  labels:
    {{- include "deepfence-console.labels" . | nindent 4 }}
    component: file-server
stringData:
  DEEPFENCE_FILE_SERVER_HOST: {{ include "deepfence-console.fullname" . }}-file-server
  DEEPFENCE_FILE_SERVER_PORT: "9000"
  DEEPFENCE_FILE_SERVER_SECURE: "false"
  DEEPFENCE_FILE_SERVER_BUCKET: default
  {{- if .Values.fileserver.secrets }}
  DEEPFENCE_FILE_SERVER_PASSWORD: {{ .Values.fileserver.secrets.FILE_SERVER_ROOT_PASSWORD | quote }}
  DEEPFENCE_FILE_SERVER_USER: {{ .Values.fileserver.secrets.FILE_SERVER_ROOT_USER | quote }}
  {{- end }}
  DEEPFENCE_FILE_SERVER_DB_BUCKET: database
{{- end }}

