{{- if .Values.fileserver.create }}
---
kind: Secret
apiVersion: v1
type: Opaque
metadata:
  name: "deepfence-console-secrets-fileserver"
  labels:
    {{- include "deepfence-console.labels" . | nindent 4 }}
    component: file-server
stringData:
  DEEPFENCE_MINIO_HOST: deepfence-file-server
  DEEPFENCE_MINIO_PORT: "9000"
  DEEPFENCE_MINIO_SECURE: "false"
  DEEPFENCE_MINIO_BUCKET: deepfence
  DEEPFENCE_MINIO_PASSWORD: {{ .Values.fileserver.secrets.MINIO_ROOT_PASSWORD | quote }}
  DEEPFENCE_MINIO_USER: {{ .Values.fileserver.secrets.MINIO_ROOT_USER | quote }}
{{- end }}

