apiVersion: v1
kind: Service
metadata:
  name: deepfence-diagnosis
  labels:
    {{- include "deepfence-console.labels" . | nindent 4 }}
    app: deepfence-console
    name: deepfence-diagnosis
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.diagnosis.service.type }}
  ports:
    - name: deepfence-diagnosis-port
      port: 8009
      protocol: TCP
      targetPort: 8009
  selector:
    {{- include "deepfence-console.selectorLabels" . | nindent 4 }}
    name: deepfence-diagnosis