FROM debian:bullseye-slim
LABEL maintainer="Deepfence Inc"
LABEL deepfence.role=system

ENV CHECKPOINT_DISABLE=true \
    DF_TLS_ON="1" \
    MGMT_CONSOLE_PORT=443 \
    DF_KUBERNETES_ON="Y" \
    MGMT_CONSOLE_URL_SCHEMA=https \
    DEEPFENCE_KEY="" \
    MGMT_CONSOLE_URL_INTERNAL=127.0.0.1 \
    MGMT_CONSOLE_PORT_INTERNAL=8081 \
    DF_ENABLE_CLUSTER_DISCOVERY="true"

WORKDIR /home/deepfence
RUN apt-get update
RUN apt-get install -y --no-install-recommends libpcap0.8 bash conntrack iproute2 util-linux curl grep tar git wget supervisor gettext htop vim ca-certificates sudo cron logrotate
RUN /bin/sh -c "$(curl -fsSL https://raw.githubusercontent.com/turbot/steampipe/v0.20.12/install.sh)"
RUN useradd -rm -d /home/deepfence -s /bin/bash -g root -G sudo -u 1001 deepfence

# Installing FluentBit
RUN mkdir -p /etc/td-agent-bit/ /root/fluentbit
COPY tools/apache/fluentbit/* /etc/td-agent-bit/

COPY etc/fenced_logrotate.conf /etc/logrotate.d/fenced_logrotate.conf

COPY start_agent.sh /usr/local/bin/start_agent
RUN chmod +x /usr/local/bin/start_agent
COPY plugins/fluent-bit/build/bin/fluent-bit /opt/td-agent-bit/bin/

WORKDIR /opt/steampipe
COPY tools/apache/scope/probe/kubernetes/kubeconfig /home/deepfence/.kube/config
COPY tools/apache/scope/probe/kubernetes/token.sh /home/deepfence/token.sh
RUN chown -R deepfence:root /opt/ /home/deepfence /var/log /var/run/ \
    && chown -R root:root /etc/td-agent-bit/ /root/fluentbit

USER deepfence
COPY supervisord-cluster.conf /home/deepfence/supervisord.conf
COPY run_discovery.sh /home/deepfence/
COPY plugins/etc/run_fluentbit.sh /home/deepfence/
RUN steampipe plugin install steampipe \
    && steampipe plugin install kubernetes \
    && git clone https://github.com/turbot/steampipe-mod-kubernetes-compliance.git

COPY tools/apache/scope/docker/discovery /home/deepfence/
COPY deepfenced /bin/deepfenced

USER root

RUN chmod +x /home/deepfence/*.sh /home/deepfence/discovery

ENTRYPOINT ["/usr/local/bin/start_agent"]
