FROM debian:bullseye-slim
LABEL maintainer="Deepfence Inc"
LABEL deepfence.role=system

ENV CHECKPOINT_DISABLE=true \
    DF_TLS_ON="1" \
    MGMT_CONSOLE_PORT=443 \
    DF_KUBERNETES_ON="Y" \
    MGMT_CONSOLE_URL_SCHEMA=https \
    DEEPFENCE_KEY="" \
    MGMT_CONSOLE_URL_INTERNAL=127.0.0.1 \
    MGMT_CONSOLE_PORT_INTERNAL=8081 \
    DF_ENABLE_CLUSTER_DISCOVERY="true" \
    STEAMPIPE_VERSION=0.24.2 \
    STEAMPIPE_KUBERNETES_PLUGIN_VERSION=0.29.0 \
    STEAMPIPE_PLUGIN_VERSION=0.10.0

WORKDIR /home/deepfence
RUN apt-get update
RUN apt-get install -y --no-install-recommends libpcap0.8 bash conntrack iproute2 util-linux curl grep tar git wget supervisor gettext htop vim ca-certificates sudo cron logrotate
RUN /bin/sh -c "$(curl -fsSL https://raw.githubusercontent.com/turbot/steampipe/refs/tags/v${STEAMPIPE_VERSION}/scripts/install.sh)"
RUN useradd -rm -d /home/deepfence -s /bin/bash -g root -G sudo -u 1001 deepfence

COPY etc/fenced_logrotate.conf /etc/logrotate.d/fenced_logrotate.conf

COPY start_agent.sh /usr/local/bin/start_agent
RUN chmod +x /usr/local/bin/start_agent
COPY plugins/deepfence_shipper/deepfence_shipper /home/deepfence/bin/shipper
COPY plugins/deepfence_shipper/routes.yaml /home/deepfence/routes.yaml

WORKDIR /opt/steampipe
COPY tools/apache/scope/probe/kubernetes/kubeconfig /home/deepfence/.kube/config
COPY tools/apache/scope/probe/kubernetes/token.sh /home/deepfence/token.sh
RUN chown -R deepfence:root /opt/ /home/deepfence /var/log /var/run/

USER deepfence
COPY supervisord-cluster.conf /home/deepfence/supervisord.conf
COPY run_discovery.sh /home/deepfence/
COPY plugins/etc/run_shipper.sh /home/deepfence/
RUN steampipe plugin install steampipe@${STEAMPIPE_PLUGIN_VERSION} \
    && steampipe plugin install kubernetes@${STEAMPIPE_KUBERNETES_PLUGIN_VERSION} \
    && git clone https://github.com/turbot/steampipe-mod-kubernetes-compliance.git --branch v0.18 --depth 1

COPY tools/apache/scope/docker/discovery /home/deepfence/
COPY deepfenced /bin/deepfenced

USER root

RUN chmod +x /home/deepfence/*.sh /home/deepfence/discovery

ENTRYPOINT ["/usr/local/bin/start_agent"]
