FROM node:24-trixie AS build-stage

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt install -y --no-install-recommends default-jre
RUN mkdir -p /app
WORKDIR /app
RUN corepack enable
RUN corepack prepare pnpm@9.15.4 --activate
COPY . .