FROM node:18-bullseye as build-stage

ENV DEBIAN_FRONTEND=noninteractive
ENV DO_NOT_TRACK=1

RUN apt-get update && apt install -y --no-install-recommends default-jre
RUN mkdir -p /app
WORKDIR /app
RUN corepack enable
RUN corepack prepare pnpm@9.10.0 --activate
COPY . .