---
{{- if .Values.registry.createRegistrySecret }}
apiVersion: v1
kind: Secret
metadata:
  name: docker-deepfence-secret
  labels:
    app: deepfence-console
    {{- include "deepfence-console.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
{{- end }}
