{{- if and .Values.db.elasticsearch.user .Values.db.elasticsearch.password }}
apiVersion: v1
data:
  es_user: {{ .Values.db.elasticsearch.user | b64enc }}
  es_password: {{ .Values.db.elasticsearch.password | b64enc }}
  {{- if eq "true" .Values.saas_deployment }}
  es_customer_unique_id: {{ .Values.namespace | b64enc }}
  {{- end }}
kind: Secret 
metadata:
  name: "es-secret-{{ include "deepfence-console.fullname" . }}"
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "deepfence-console.labels" . | nindent 4 }}
type: Opaque
{{- end }}