kind: Secret 
apiVersion: v1
metadata:
  name: "es-secret-{{ include "deepfence-console.fullname" . }}"
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "deepfence-console.labels" . | nindent 4 }}
type: Opaque
data:
  es_scheme: {{ .Values.db.elasticsearch.scheme | b64enc }}
  es_host: {{ .Values.db.elasticsearch.host | b64enc }}
  es_port: {{ .Values.db.elasticsearch.port | default 9200 | b64enc }}
  {{- if and .Values.db.elasticsearch.user .Values.db.elasticsearch.password }}
  es_user: {{ .Values.db.elasticsearch.user | b64enc }}
  es_password: {{ .Values.db.elasticsearch.password | b64enc }}
  {{- end }}
  {{- if .Values.saas_deployment }}
  es_customer_unique_id: {{ .Release.Namespace | b64enc }}
  {{- end }}
