{{- if and .Values.tls.cert .Values.tls.key }}
apiVersion: v1
kind: Secret
metadata:
  name: deepfence-ui-ssl-cert
  labels:
    app: deepfence-console
    {{- include "deepfence-console.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/tls
data:
  tls.crt: |-
{{ .Values.tls.cert | b64enc | indent 4}}
  tls.key: |-
{{ .Values.tls.key | b64enc | indent 4}}
{{- end }}