{{- if .Values.saas_deployment }}
apiVersion: v1
data:
  pg_host: {{ .Values.db.postgresUserDb.host | b64enc }}
  pg_port: {{ .Values.db.postgresUserDb.port | b64enc }}
  pg_root_user: {{ .Values.db.postgresUserDb.user | b64enc }}
  pg_root_password: {{ .Values.db.postgresUserDb.password | b64enc }}
  pg_user: {{ .Values.db.postgresUserDb.customer_user_name | b64enc }}
  pg_password: {{ .Values.db.postgresUserDb.customer_user_password | b64enc }}
  pg_users_db_name: {{ .Values.db.postgresUserDb.dbname | b64enc }}
  pg_ssl_mode: {{ .Values.db.postgresUserDb.sslmode | b64enc }}
kind: Secret
metadata:
  name: "pg-secret-{{ include "deepfence-console.fullname" . }}"
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "deepfence-console.labels" . | nindent 4 }}
type: Opaque
{{- end }}