---
apiVersion: v1
kind: Service
metadata:
  name: deepfence-fetcher
  labels:
    {{- include "deepfence-console.labels" . | nindent 4 }}
    app: deepfence-console
    name: deepfence-fetcher
  namespace: {{ .Release.Namespace }}
spec:
  type:  {{ .Values.fetcher.service.type }}
  selector:
    name: deepfence-fetcher
  ports:
    - name: deepfence-fetcher-port-1
      port: 8001
      protocol: TCP
      targetPort: 8001
    - name: deepfence-fetcher-port-2
      port: 8002
      protocol: TCP
      targetPort: 8002
    - name: deepfence-fetcher-port-3
      port: 8006
      protocol: TCP
      targetPort: 8006

