FROM debian:bullseye-slim
LABEL maintainer="Deepfence Inc"
LABEL deepfence.role=system

ENV DOCKERVERSION=24.0.2 MGMT_CONSOLE_PORT=443

WORKDIR /home/deepfence
RUN apt-get update
RUN apt-get install -y bash conntrack iproute2 util-linux curl grep tar git wget supervisor gettext htop vim ca-certificates \
    && apt-get -y --allow-unauthenticated install podman \
    && curl -fsSLO https://download.docker.com/linux/static/stable/x86_64/docker-${DOCKERVERSION}.tgz \
    && tar xzvf docker-${DOCKERVERSION}.tgz --strip 1 -C /usr/local/bin docker/docker \
    && rm docker-${DOCKERVERSION}.tgz \
    && curl -fsSLOk https://github.com/deepfence/vessel/releases/download/v0.11.0/vessel_v0.11.0_linux_amd64.tar.gz \
    && tar -xzf vessel_v0.11.0_linux_amd64.tar.gz \
    && mv vessel /usr/local/bin/ \
    && rm -rf vessel_v0.11.0_linux_amd64.tar.gz \
    && nerdctl_version=1.4.0 \
    && curl -fsSLOk https://github.com/containerd/nerdctl/releases/download/v${nerdctl_version}/nerdctl-${nerdctl_version}-linux-amd64.tar.gz \
    && tar Cxzvvf /usr/local/bin nerdctl-${nerdctl_version}-linux-amd64.tar.gz \
    && rm nerdctl-${nerdctl_version}-linux-amd64.tar.gz \
    && VERSION="v1.27.0" \
    && curl -L https://github.com/kubernetes-sigs/cri-tools/releases/download/$VERSION/crictl-${VERSION}-linux-amd64.tar.gz --output crictl-${VERSION}-linux-amd64.tar.gz \
    && tar zxvf crictl-$VERSION-linux-amd64.tar.gz -C /usr/local/bin \
    && rm -f crictl-$VERSION-linux-amd64.tar.gz \
	&& rm -rf /var/cache/apk/* \
    && /bin/sh -c "$(curl -fsSL https://raw.githubusercontent.com/turbot/steampipe/main/install.sh)" \
    && useradd -rm -d /home/deepfence -s /bin/bash -g root -G sudo -u 1001 deepfence

# Installing FluentBit
RUN wget -qO - https://packages.fluentbit.io/fluentbit.key | apt-key add - \
    && echo "deb https://packages.fluentbit.io/debian/buster buster main " >> /etc/apt/sources.list \
    && apt-get update --allow-insecure-repositories \
    && apt-get install -y td-agent-bit=1.6.10 && mkdir -p /etc/td-agent-bit/

COPY fluentbit/* /etc/td-agent-bit/
COPY scope/docker/fluent-bit.conf /etc/td-agent-bit/td-agent-bit.conf
COPY fluentbit/out_deepfence/out_deepfence.so /opt/td-agent-bit/bin/
USER deepfence
COPY scope/docker/deepfence_exe /home/deepfence/
COPY deepfence/supervisord_cluster_agent.conf /home/deepfence/supervisord-temp.conf
COPY scope/docker/run_cluster_agent.sh /home/deepfence/
COPY scope/docker/entrypoint.sh /home/deepfence/

WORKDIR /opt/steampipe
USER root
COPY scope/probe/kubernetes/kubeconfig /home/deepfence/.kube/config
COPY scope/probe/kubernetes/token.sh /home/deepfence/token.sh
RUN chown -R deepfence /opt/ /home/deepfence /var/log /var/run/ /etc/td-agent-bit/ \
    && chmod +x /home/deepfence/*.sh

USER deepfence
RUN steampipe plugin install steampipe \
    && steampipe plugin install kubernetes \
    && git clone https://github.com/turbot/steampipe-mod-kubernetes-compliance.git

ENTRYPOINT ["/home/deepfence/entrypoint.sh"]
