FROM alpine:3.14.2
LABEL maintainer="Deepfence Inc"
LABEL deepfence.role=system

ENV CHECKPOINT_DISABLE=true DOCKERVERSION=20.10.8

WORKDIR /home/deepfence
RUN apk add --no-cache --update bash conntrack-tools iproute2 util-linux curl bind-tools grep \
    && curl -fsSLO https://download.docker.com/linux/static/stable/x86_64/docker-${DOCKERVERSION}.tgz \
    && tar xzvf docker-${DOCKERVERSION}.tgz --strip 1 -C /usr/local/bin docker/docker \
    && rm docker-${DOCKERVERSION}.tgz \
	&& rm -rf /var/cache/apk/*
COPY ./deepfence_exe /home/deepfence/
# COPY ./capture_topology_container.sh /home/deepfence/capture_start.sh
# RUN cp /home/deepfence/capture_start.sh /home/deepfence/capture_stop.sh \
#     && cp /home/deepfence/capture_start.sh /home/deepfence/capture_status.sh \
#     && chmod +x /home/deepfence/*.sh
ENTRYPOINT ["/home/deepfence/deepfence_exe"]
