FROM debian:bullseye-slim
LABEL maintainer="Deepfence Inc"
LABEL deepfence.role=system

ENV CHECKPOINT_DISABLE=true DOCKERVERSION=20.10.8 MGMT_CONSOLE_PORT=443

WORKDIR /home/deepfence
RUN apt-get update
RUN apt-get install -y bash conntrack iproute2 util-linux curl grep tar git wget supervisor gettext \
    && apt-get -y --allow-unauthenticated install podman \
    && curl -fsSLO https://download.docker.com/linux/static/stable/x86_64/docker-${DOCKERVERSION}.tgz \
    && tar xzvf docker-${DOCKERVERSION}.tgz --strip 1 -C /usr/local/bin docker/docker \
    && rm docker-${DOCKERVERSION}.tgz \
    && curl -fsSLOk https://github.com/deepfence/vessel/releases/download/v0.9.0/vessel_v0.9.0_linux_amd64.tar.gz \
    && tar -xzf vessel_v0.9.0_linux_amd64.tar.gz \
    && mv vessel /usr/local/bin/ \
    && rm -rf vessel_v0.9.0_linux_amd64.tar.gz \
    && curl -fsSLOk https://github.com/containerd/nerdctl/releases/download/v1.1.0/nerdctl-1.1.0-linux-amd64.tar.gz \
    && tar Cxzvvf /usr/local/bin nerdctl-1.1.0-linux-amd64.tar.gz \
    && rm nerdctl-1.1.0-linux-amd64.tar.gz \
    && VERSION="v1.26.0" \
    && curl -L https://github.com/kubernetes-sigs/cri-tools/releases/download/$VERSION/crictl-${VERSION}-linux-amd64.tar.gz --output crictl-${VERSION}-linux-amd64.tar.gz \
    && tar zxvf crictl-$VERSION-linux-amd64.tar.gz -C /usr/local/bin \
    && rm -f crictl-$VERSION-linux-amd64.tar.gz \
	&& rm -rf /var/cache/apk/* \
    && /bin/sh -c "$(curl -fsSL https://raw.githubusercontent.com/turbot/steampipe/main/install.sh)" \
    && useradd -rm -d /home/deepfence -s /bin/bash -g root -G sudo -u 1001 deepfence

# Installing FluentBit
RUN wget -qO - https://packages.fluentbit.io/fluentbit.key | apt-key add - \
    && echo "deb https://packages.fluentbit.io/debian/buster buster main " >> /etc/apt/sources.list \
    && apt-get update --allow-insecure-repositories \
    && apt-get install -y td-agent-bit=1.6.10 && mkdir -p /etc/td-agent-bit/

COPY scope/docker/fluent-bit.conf /etc/td-agent-bit/td-agent-bit.conf
COPY fluentbit/out_deepfence/out_deepfence.so /opt/td-agent-bit/bin/
USER deepfence
COPY scope/docker/deepfence_exe /home/deepfence/
COPY deepfence/supervisord_cluster_agent.conf /home/deepfence/supervisord-temp.conf
COPY deepfence/start_cluster_agent.sh /usr/local/bin/start_services

WORKDIR /opt/steampipe
USER root
COPY scope/probe/kubernetes/kubeconfig /home/deepfence/.kube/config
COPY scope/probe/kubernetes/token.sh /home/deepfence/token.sh
RUN chown -R deepfence /opt/steampipe /home/deepfence /home/deepfence /var/log /usr/local/bin/start_services /var/run/ \
     && chmod +x /usr/local/bin/start_services

USER deepfence
RUN steampipe plugin install steampipe \
    && steampipe plugin install kubernetes \
    && git clone https://github.com/turbot/steampipe-mod-kubernetes-compliance.git

ENTRYPOINT ["/usr/local/bin/start_services"]
