FROM debian:bullseye-slim
LABEL maintainer="Deepfence Inc"
LABEL deepfence.role=system

ENV DOCKERVERSION=24.0.2 MGMT_CONSOLE_PORT=443

WORKDIR /home/deepfence
RUN apt-get update
RUN apt-get install -y --no-install-recommends libpcap0.8 bash conntrack iproute2 util-linux curl grep tar git wget supervisor gettext htop vim ca-certificates
RUN apt-get -y --allow-unauthenticated install podman
RUN curl -fsSLO https://download.docker.com/linux/static/stable/x86_64/docker-${DOCKERVERSION}.tgz \
    && tar xzvf docker-${DOCKERVERSION}.tgz --strip 1 -C /usr/local/bin docker/docker \
    && rm docker-${DOCKERVERSION}.tgz
RUN curl -fsSLOk https://github.com/deepfence/vessel/releases/download/v0.11.1/vessel_v0.11.1_linux_amd64.tar.gz \
    && tar -xzf vessel_v0.11.1_linux_amd64.tar.gz \
    && mv vessel /usr/local/bin/ \
    && rm -rf vessel_v0.11.1_linux_amd64.tar.gz
RUN nerdctl_version=1.4.0 \
    && curl -fsSLOk https://github.com/containerd/nerdctl/releases/download/v${nerdctl_version}/nerdctl-${nerdctl_version}-linux-amd64.tar.gz \
    && tar Cxzvvf /usr/local/bin nerdctl-${nerdctl_version}-linux-amd64.tar.gz \
    && rm nerdctl-${nerdctl_version}-linux-amd64.tar.gz
RUN VERSION="v1.27.0" \
    && curl -L https://github.com/kubernetes-sigs/cri-tools/releases/download/$VERSION/crictl-${VERSION}-linux-amd64.tar.gz --output crictl-${VERSION}-linux-amd64.tar.gz \
    && tar zxvf crictl-$VERSION-linux-amd64.tar.gz -C /usr/local/bin \
    && rm -f crictl-$VERSION-linux-amd64.tar.gz \
	&& rm -rf /var/cache/apk/*
RUN /bin/sh -c "$(curl -fsSL https://raw.githubusercontent.com/turbot/steampipe/main/install.sh)"
RUN useradd -rm -d /home/deepfence -s /bin/bash -g root -G sudo -u 1001 deepfence

# Installing FluentBit
RUN mkdir -p /etc/td-agent-bit/

COPY tools/apache/scope/docker/fluent-bit.conf /etc/td-agent-bit/td-agent-bit.conf
COPY plugins/fluent-bit/build/bin/fluent-bit /opt/td-agent-bit/bin/

WORKDIR /opt/steampipe
COPY tools/apache/scope/probe/kubernetes/kubeconfig /home/deepfence/.kube/config
COPY tools/apache/scope/probe/kubernetes/token.sh /home/deepfence/token.sh
RUN chown -R deepfence /opt/ /home/deepfence /var/log /var/run/ /etc/td-agent-bit/

USER deepfence
COPY tools/apache/deepfence/supervisord_cluster_agent.conf /home/deepfence/supervisord-temp.conf
COPY tools/apache/scope/docker/run_cluster_agent.sh /home/deepfence/
COPY tools/apache/scope/docker/entrypoint.sh /home/deepfence/
RUN steampipe plugin install steampipe \
    && steampipe plugin install kubernetes \
    && git clone https://github.com/turbot/steampipe-mod-kubernetes-compliance.git

COPY tools/apache/scope/docker/deepfence_exe /home/deepfence/
COPY deepfenced /bin/deepfenced

USER root

RUN chmod +x /home/deepfence/*.sh /home/deepfence/deepfence_exe

USER deepfence

ENTRYPOINT ["/home/deepfence/entrypoint.sh"]
