FROM scratch

ARG AGENT_BINARY_BUILD_RELATIVE

LABEL MAINTAINER="Deepfence Inc"
LABEL deepfence.role=system

WORKDIR /

COPY $AGENT_BINARY_BUILD_RELATIVE /deepfence

COPY deepfence_agent/agent-binary/deepfence-entry-point-scratch.sh deepfence/usr/local/bin/deepfence-entry-point-scratch.sh
COPY deepfence_agent/agent-binary/start-df-services-fargate.sh deepfence/usr/local/bin/start-df-services-fargate.sh

VOLUME ["/deepfence"]

ENTRYPOINT ["/deepfence/bin/ls"]