---
apiVersion: v1
kind: Service
metadata:
  name: deepfence-redis
  labels:
    {{- include "deepfence-console.labels" . | nindent 4 }}
    app: deepfence-console
    name: deepfence-redis
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.redis.service.type }}
  selector:
    {{- include "deepfence-console.selectorLabels" . | nindent 4 }}
    name: deepfence-redis
  ports:
    - name: deepfence-redis-port
      port: 6379
      protocol: TCP
      targetPort: 6379