/*
Deepfence ThreatMapper

Deepfence Runtime API provides programmatic control over Deepfence microservice securing your container, kubernetes and cloud deployments. The API abstracts away underlying infrastructure details like cloud provider,  container distros, container orchestrator and type of deployment. This is one uniform API to manage and control security alerts, policies and response to alerts for microservices running anywhere i.e. managed pure greenfield container deployments or a mix of containers, VMs and serverless paradigms like AWS Fargate.

API version: 2.0.0
Contact: community@deepfence.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package deepfence_server_client

import (
	"encoding/json"
)

// checks if the ControlsScanResource type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ControlsScanResource{}

// ControlsScanResource struct for ControlsScanResource
type ControlsScanResource struct {
	Enum string `json:"enum"`
}

// NewControlsScanResource instantiates a new ControlsScanResource object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewControlsScanResource(enum string) *ControlsScanResource {
	this := ControlsScanResource{}
	this.Enum = enum
	return &this
}

// NewControlsScanResourceWithDefaults instantiates a new ControlsScanResource object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewControlsScanResourceWithDefaults() *ControlsScanResource {
	this := ControlsScanResource{}
	return &this
}

// GetEnum returns the Enum field value
func (o *ControlsScanResource) GetEnum() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Enum
}

// GetEnumOk returns a tuple with the Enum field value
// and a boolean to check if the value has been set.
func (o *ControlsScanResource) GetEnumOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Enum, true
}

// SetEnum sets field value
func (o *ControlsScanResource) SetEnum(v string) {
	o.Enum = v
}

func (o ControlsScanResource) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ControlsScanResource) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["enum"] = o.Enum
	return toSerialize, nil
}

type NullableControlsScanResource struct {
	value *ControlsScanResource
	isSet bool
}

func (v NullableControlsScanResource) Get() *ControlsScanResource {
	return v.value
}

func (v *NullableControlsScanResource) Set(val *ControlsScanResource) {
	v.value = val
	v.isSet = true
}

func (v NullableControlsScanResource) IsSet() bool {
	return v.isSet
}

func (v *NullableControlsScanResource) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableControlsScanResource(val *ControlsScanResource) *NullableControlsScanResource {
	return &NullableControlsScanResource{value: val, isSet: true}
}

func (v NullableControlsScanResource) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableControlsScanResource) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


