apiVersion: v1
kind: Service
metadata:
  name: deepfence-vulnerability-mapper
  labels:
    {{- include "deepfence-console.labels" . | nindent 4 }}
    app: deepfence-console
    name: deepfence-vulnerability-mapper
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    {{- include "deepfence-console.selectorLabels" . | nindent 4 }}
    name: deepfence-vulnerability-mapper
  ports:
  - name: deepfence-vulnerability-mapper-port
    port: 8001
    protocol: TCP
    targetPort: 8001