{{- if .Values.minio.create }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: deepfence-file-server
  labels:
    {{- include "deepfence-console.labels" . | nindent 4 }}
    component: minio
    name: deepfence-file-server
spec:
  serviceName: deepfence-file-server
  replicas: 1
  selector:
    matchLabels:
      {{- include "deepfence-console.selectorLabels" . | nindent 6 }}
      component: minio
      name: deepfence-file-server
  template:
    metadata:
      {{- with .Values.minio.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "deepfence-console.selectorLabels" . | nindent 8 }}
        component: minio
        name: deepfence-file-server
    spec:
      serviceAccountName: {{ include "deepfence-console.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.minio.podSecurityContext | nindent 8 }}
      containers:
        - name: minio
          securityContext:
            {{- toYaml .Values.minio.securityContext | nindent 12 }}
          image: "{{ .Values.global.imageRepoPrefix }}/{{ .Values.minio.image.repository }}:{{ default .Values.global.imageTag .Values.minio.image.tag }}"
          imagePullPolicy: {{ .Values.minio.image.pullPolicy }}
          envFrom:
            - secretRef:
                name: "deepfence-file-server"
          ports:
            - name: http
              containerPort: 9000
              protocol: TCP
            - name: ui
              containerPort: 9090
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 60
            periodSeconds: 30
          readinessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 60
            periodSeconds: 30
          resources:
            {{- toYaml .Values.minio.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /data
              name: "file-server-{{ .Release.Name }}"
      {{- with .Values.minio.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.minio.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.minio.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  volumeClaimTemplates:
    - metadata:
        name: "file-server-{{ .Release.Name }}"
      spec:
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            storage: "{{ .Values.minio.volumeSize }}"
        storageClassName: {{ .Values.minio.storageClass }}
---
apiVersion: v1
kind: Service
metadata:
  name: deepfence-file-server
  labels:
    {{- include "deepfence-console.labels" . | nindent 4 }}
    component: minio
    name: deepfence-file-server
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 9000
      targetPort: http
      protocol: TCP
    - name: ui
      port: 9090
      targetPort: ui
      protocol: TCP
  selector:
    {{- include "deepfence-console.selectorLabels" . | nindent 4 }}
    component: minio
    name: deepfence-file-server
{{- end }}