name: secrets-scanner

on:
  push:
    branches:
    - "*"
  pull_request:
    branches:
    - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GROUP: deepfence
      COMMIT: ${{ github.sha }}
      REPO: demo-app
      DEEPFENCE_CONSOLE_URL: 127.0.0.1
      DEEPFENCE_KEY: key
    steps:
    - uses: actions/checkout@v2

    # Build docker image for service
    - name: Build docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: false
        tags: ${{ env.GROUP }}/${{ env.REPO }}:${{ github.sha }}

    # Run Deepfence Secrets Scanner to check for secrets in image
    - name: Run Deepfence Secrets Scanner
      env:
        DEEPFENCE_CONSOLE_URL: ${{ env.DEEPFENCE_CONSOLE_URL }}
        DEEPFENCE_KEY: ${{ env.DEEPFENCE_KEY }}
        FULL_IMAGE_NAME: ${{ env.GROUP }}/${{ env.REPO }}:${{ github.sha }}
        FAIL_SECRET_COUNT: 100 # Fail build if number of secrets found is >= this number. Set -1 to pass regardless of secrets.
        FAIL_HIGH_SECRET_COUNT: 10 # Fail build if number of high secrets found is >= this number. Set -1 to pass regardless of high secrets.
        FAIL_MEDIUM_SECRET_COUNT: 20 # Fail build if number of medium secrets found is >= this number. Set -1 to pass regardless of medium secrets.
        FAIL_LOW_SECRET_COUNT: 50 # Fail build if number of low secrets found is >= this number. Set -1 to pass regardless of low secrets.
      run: |
        docker pull deepfenceio/deepfence_secret_scanner_ce:v2
        docker run -i --rm --net=host --privileged=true --cpus=\"0.3\" -v /var/run/docker.sock:/var/run/docker.sock:rw deepfenceio/deepfence_secret_scanner_ce:v2 -image-name "$FULL_IMAGE_NAME" -fail-on-count=$FAIL_SECRET_COUNT -fail-on-high-count=$FAIL_HIGH_SECRET_COUNT -fail-on-medium-count=$FAIL_MEDIUM_SECRET_COUNT -fail-on-low-count=$FAIL_LOW_SECRET_COUNT"

    # Push to dockerhub
    - name: Push to Docker Hub
      uses: docker/build-push-action@v4
      if: startsWith(github.ref, 'refs/tags/v') || github.ref == 'refs/heads/master'
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASS }}
        tags: ${{ env.GROUP }}/${{ env.REPO }}:${{ github.sha }}