apiVersion: v1
kind: Service
metadata:
  name: deepfence-package-scanner
  labels:
    {{- include "deepfence-console.labels" . | nindent 4 }}
    app: deepfence-console
    name: deepfence-package-scanner
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    {{- include "deepfence-console.selectorLabels" . | nindent 4 }}
    name: deepfence-package-scanner
  ports:
  - name: deepfence-package-scanner-port
    port: 8005
    protocol: TCP
    targetPort: 8005