apiVersion: v1
kind: Service
metadata:
  name: deepfence-topology
  labels:
    {{- include "deepfence-console.labels" . | nindent 4 }}
    app: deepfence-console
    name: deepfence-service
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.topology.service.type }}
  ports:
    - name: deepfence-topology-port
      port: 8004
      protocol: TCP
      targetPort: 8004

  selector:
    {{- include "deepfence-console.selectorLabels" . | nindent 4 }}
    name: deepfence-topology