{{- if and (eq "deepfence-redis" .Values.db.redis.host) (eq "6379" .Values.db.redis.port) }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deepfence-redis
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "deepfence-console.labels" . | nindent 4 }}
    app: deepfence-console
    name: deepfence-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      name: deepfence-redis
      {{- include "deepfence-console.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: deepfence-console
        name: deepfence-redis
        {{- include "deepfence-console.selectorLabels" . | nindent 8 }}
    spec:
      initContainers:
      - name: init-sysctl
        image: busybox:latest
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: true
        command:
        - /bin/sh
        - -c
        - |
          sysctl -w fs.file-max=1048576
          sysctl -w net.core.somaxconn=512
          sysctl vm.overcommit_memory=1
      imagePullSecrets:
        - name: {{ .Values.image.pullSecretName }}
      serviceAccountName: {{ .Values.serviceAccountName }}
      containers:
        - name: deepfence-redis
          image: "{{ .Values.redis.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: Always
          env:
            - name: INITIALIZE_REDIS
              value: "Y"
          ports:
            - containerPort: 6379
          resources:
            requests:
              cpu: {{ .Values.defaultResourceLimits.requests.cpu }}
              memory: {{ .Values.defaultResourceLimits.requests.memory }}
            limits:
{{- if eq "true" .Values.setDefaultResourceLimits }}
              cpu: {{ .Values.defaultResourceLimits.limits.cpu }}
{{- end }}
              memory: 10Gi
      {{- with .Values.redis.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- if .Values.topologyNodeAffinityHostName }}
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: NotIn
                    values:
                      - "{{ .Values.topologyNodeAffinityHostName }}"
{{- end }}
      {{- with .Values.redis.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}