{{- if .Values.fileserver.create }}
---
kind: Secret
apiVersion: v1
type: Opaque
metadata:
  name: "deepfence-file-server"
  labels:
    {{- include "deepfence-console.labels" . | nindent 4 }}
    component: fileserver
stringData:
    {{- range $k, $v := .Values.fileserver.secrets }}
    {{ $k }}: {{ $v }}
    {{- end }}
{{- end }}