---
{{- if .Values.imagePullSecret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "deepfence-agent.imagePullSecretName" . }}
  labels:
    {{- include "deepfence-agent.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: "{{ template "imagePullSecret" . }}"
{{- end }}
---
{{- if .Values.createDeepfenceKeySecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "deepfence-agent.fullname" . }}-key
  labels:
    {{- include "deepfence-agent.labels" . | nindent 4 }}
type: Opaque
data:
  deepfence-key: {{ required "deepfenceKey is required" .Values.deepfenceKey | b64enc }}
{{- end }}
