"""empty message

Revision ID: 91291feb3173
Revises: 7ba0e6423863
Create Date: 2022-05-31 01:59:21.467825

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91291feb3173'
down_revision = '7ba0e6423863'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cloud_compliance_node',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('node_id', sa.String(length=200), nullable=False),
    sa.Column('node_name', sa.String(length=200), nullable=False),
    sa.Column('cloud_provider', sa.String(length=200), nullable=False),
    sa.Column('compliance_percentage', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cloud_compliance_node')
    # ### end Alembic commands ###
