"""empty message

Revision ID: 9b57e8e330bd
Revises: 7c96a8cfb1b4
Create Date: 2023-01-16 13:39:45.586786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b57e8e330bd'
down_revision = '7c96a8cfb1b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cloud_resource_node', sa.Column('last_scanned_time', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cloud_resource_node', 'last_scanned_time')
    # ### end Alembic commands ###