"""empty message

Revision ID: c1d784814e05
Revises: 6c21af9ffff5
Create Date: 2022-05-23 07:53:32.470228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1d784814e05'
down_revision = '6c21af9ffff5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('compliance_rules', sa.Column('cloud_provider', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('compliance_rules', 'cloud_provider')
    # ### end Alembic commands ###