"""empty message

Revision ID: dd9449735f82
Revises: df2b403f31a6
Create Date: 2022-07-20 08:28:13.998471

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd9449735f82'
down_revision = 'df2b403f31a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cloud_resource_node', sa.Column('service_name', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cloud_resource_node', 'service_name')
    # ### end Alembic commands ###