{{- if eq "false" .Values.saas_deployment }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deepfence-ui
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "deepfence-console.labels" . | nindent 4 }}
    app: deepfence-console
    name: deepfence-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      name: deepfence-ui
      {{- include "deepfence-console.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: deepfence-console
        name: deepfence-ui
        {{- include "deepfence-console.selectorLabels" . | nindent 8 }}
    spec:
      imagePullSecrets:
        - name: {{ .Values.image.pullSecretName }}
      serviceAccountName: {{ .Values.serviceAccountName }}
      containers:
        - name: deepfence-ui
          image: "{{ .Values.ui.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: Always
          ports:
            - containerPort: 4042
          resources:
            requests:
              memory: {{ .Values.defaultResourceLimits.requests.memory }}
              cpu: {{ .Values.defaultResourceLimits.requests.cpu }}
            limits:
              memory: 512Mi
{{- if eq "true" .Values.setDefaultResourceLimits }}
              cpu: {{ .Values.defaultResourceLimits.limits.cpu }}
{{- end }}
      {{- with .Values.ui.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- if .Values.topologyNodeAffinityHostName }}
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: NotIn
                    values:
                      - "{{ .Values.topologyNodeAffinityHostName }}"
{{- end }}
      {{- with .Values.ui.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
