FROM golang:1.18-bullseye AS build
RUN apt-get update \
    && apt-get install -y bash make git gcc \
    && cd /go \
    && git clone --depth 1 -b v0.44.1 https://github.com/deepfence/syft \
    && cd /go/syft \
    && go build -v -o syftCli .

FROM scratch

MAINTAINER Deepfence Inc
LABEL deepfence.role=system

WORKDIR /

COPY tools/apache/scope/docker/deepfence_exe deepfence/usr/local/discovery/deepfence-discovery
COPY fargate/bin/ deepfence/bin/
COPY etc/certs/* deepfence/etc/filebeat/
COPY plugins/docker_bin/ deepfence/bin/
COPY --from=build /go/syft/syftCli /deepfence/usr/local/bin/syft

COPY run_discovery.sh /deepfence/home/deepfence/
COPY fargate/run_discovery_loop.sh /deepfence/home/deepfence/

COPY tools/apache/scope/docker/uploadFile.sh deepfence/home/deepfence/uploadFile.sh

ADD fargate/misc/scanners-1.3.0.tar.gz /deepfence/home/deepfence/

COPY misc/deepfence/df-utils/agent_auth/agentAuth /deepfence/usr/local/bin/agentAuth
COPY misc/deepfence/df-utils/get_cloud_instance_id/getCloudInstanceId /deepfence/usr/local/bin/getCloudInstanceId
COPY tools/apache/scope/docker/deepfenceutil /deepfence/usr/bin/deepfenceutil

COPY fargate/deepfence-entry-point-scratch.sh deepfence/usr/local/bin/deepfence-entry-point-scratch.sh
COPY fargate/start-df-services.sh deepfence/usr/local/bin/start-df-services.sh

ENTRYPOINT ["/deepfence/bin/ls"]

VOLUME ["/deepfence"]
