apiVersion:  apps/v1
kind: Deployment
metadata:
  name: deepfence-vulnerability-mapper
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "deepfence-console.labels" . | nindent 4 }}
    app: deepfence-console
    name: deepfence-vulnerability-mapper
spec:
  {{- if not .Values.vulnerabilityMapper.autoscaling.enabled }}
  replicas: {{ .Values.vulnerabilityMapper.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      name: deepfence-vulnerability-mapper
      {{- include "deepfence-console.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: deepfence-console
        name: deepfence-vulnerability-mapper
        {{- include "deepfence-console.selectorLabels" . | nindent 8 }}
    spec:
{{- if .Values.topologyNodeAffinityHostName }}
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: NotIn
                values:
                - "{{ .Values.topologyNodeAffinityHostName }}"
{{- end }}
      imagePullSecrets:
        - name: {{ .Values.image.pullSecretName }}
      containers:
      - image: "{{ .Values.vulnerabilityMapper.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.vulnerabilityMapper.image.pullPolicy }}
        name: deepfence-vulnerability-mapper
        ports:
        - containerPort: 8001
        {{- if eq "true" .Values.saas_deployment }}
        env:
            - name: CUSTOMER_UNIQUE_ID
              valueFrom:
                secretKeyRef:
                  name: "es-secret-{{ include "deepfence-console.fullname" . }}"
                  key: es_customer_unique_id
        {{- end }}
        resources:
          requests:
            memory: 100Mi
            cpu: {{ .Values.defaultResourceLimits.requests.cpu }}
{{- if eq "true" .Values.setDefaultResourceLimits }}
          limits:
            cpu: {{ .Values.defaultResourceLimits.limits.cpu }}
            memory: {{ .Values.defaultResourceLimits.limits.memory }}
{{- end }}
