apiVersion:  apps/v1
kind: Deployment
metadata:
  name: deepfence-package-scanner
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "deepfence-console.labels" . | nindent 4 }}
    app: deepfence-console
    name: deepfence-package-scanner
spec:
  {{- if not .Values.packageScanner.autoscaling.enabled }}
  replicas: {{ .Values.packageScanner.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      name: deepfence-package-scanner
      {{- include "deepfence-console.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: deepfence-console
        name: deepfence-package-scanner
        {{- include "deepfence-console.selectorLabels" . | nindent 8 }}
    spec:
{{- if .Values.topologyNodeAffinityHostName }}
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: name
                operator: In
                values:
                - deepfence-package-scanner
            topologyKey: kubernetes.io/hostname
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: NotIn
                values:
                - "{{ .Values.topologyNodeAffinityHostName }}"
{{- end }}
      imagePullSecrets:
        - name: {{ .Values.image.pullSecretName }}
      containers:
        - name: deepfence-package-scanner
          imagePullPolicy: {{ .Values.packageScanner.image.pullPolicy }}
          image: "{{ .Values.packageScanner.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          command: ["/usr/local/bin/package-scanner"]
          args: ["-mode", "http-server", "-port", "8005"]
          env:
            - name: MGMT_CONSOLE_URL
              value: "deepfence-internal-router"
            - name: MGMT_CONSOLE_PORT
              value: "443"
            - name: PACKAGE_SCAN_CONCURRENCY
              value: "5"
            {{- if eq "true" .Values.saas_deployment }}
            - name: CUSTOMER_UNIQUE_ID
              valueFrom:
                secretKeyRef:
                  name: "es-secret-{{ include "deepfence-console.fullname" . }}"
                  key: es_customer_unique_id
            {{- end }}
          ports:
          - containerPort: 8005
          resources:
            requests:
              memory: 1Gi
              cpu: {{ .Values.defaultResourceLimits.requests.cpu }}
{{- if eq "true" .Values.setDefaultResourceLimits }}
            limits:
              cpu: {{ .Values.defaultResourceLimits.limits.cpu }}
              memory: {{ .Values.defaultResourceLimits.limits.memory }}
{{- end }}